### ISSUE TITLE
Example usage doesn't seem to be complete

### ISSUE THREAD

**Issue by XanderEmu** [krzysztof-gzocha/searcher-bundle#15]
For example there's nothing about how \AgeRangeModel or \AgeRangeImposer should look like? Too many shortcuts.

Also you could add some color to examples which would make them much more readable. While creating a docblock in markdown you can specify a language.

Example:

```
function sadPHPFunction()
{
    echo 'There is no color in my life';
}
```

``` php
function happyPHPFunction()
{
    echo 'My life is full of color :) ';
}
```

**Comment by krzysztof-gzocha** [comment]
That's very nice idea. I would love it to look like this. Would you like to improve this README.md file in pull request?

**Comment by XanderEmu** [comment]
sure

**Comment by krzysztof-gzocha** [comment]
Pull request #16 fixed colors of code blocks.
Classes `\AgeRangeFilterModel` and `\AgeRangeFilterImposer` are described in example of usage in https://github.com/krzysztof-gzocha/searcher/pull/18
Do you think their implementation should be also copied to this readme file?
What about rest of the "shortcuts"? Have any idea how to fix them?

**Comment by XanderEmu** [comment]
The most convenient for users would be to see a full example on one page (that's for lazy people and yes - I am a lazy person :) ).

**Comment by krzysztof-gzocha** [comment]
I guess it's fixed now and we can close this issue. Thank you for pointing this out
