### ISSUE TITLE
Integrate with Elastica

### ISSUE THREAD

**Issue by krzysztof-gzocha** [krzysztof-gzocha/searcher-bundle#3]
Create a service that will return `ElasticaSearchingContext` (created [here](https://github.com/krzysztof-gzocha/searcher/issues/3)) that can be used for further searches.

Links to start:
- https://github.com/krzysztof-gzocha/searcher/issues/3
- https://packagist.org/packages/friendsofsymfony/elastica-bundle

**Comment by piotr-cleverbytes** [comment]
@krzysztof-gzocha i can take this one :)

**Comment by krzysztof-gzocha** [comment]
Great, thank you :)

**Comment by krzysztof-gzocha** [comment]
@ustrugany Is there any progress with this issue? :)

**Comment by krzysztof-gzocha** [comment]
This SearchingContext is already implemented in searcher library
